# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from data import data_pb2 as data_dot_data__pb2


class DataServerStub(object):
  """A simple service for writing an int data array to a server,
  and returning pertinent data in a response int array. 
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WriteIntDataArray = channel.unary_unary(
        '/dataArray.DataServer/WriteIntDataArray',
        request_serializer=data_dot_data__pb2.IntDataArray.SerializeToString,
        response_deserializer=data_dot_data__pb2.ServerSendResponse.FromString,
        )
    self.GetIntDataArrays = channel.unary_stream(
        '/dataArray.DataServer/GetIntDataArrays',
        request_serializer=data_dot_data__pb2.GetIntDataArrayStreamRequest.SerializeToString,
        response_deserializer=data_dot_data__pb2.IntDataArray.FromString,
        )


class DataServerServicer(object):
  """A simple service for writing an int data array to a server,
  and returning pertinent data in a response int array. 
  """

  def WriteIntDataArray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetIntDataArrays(self, request, context):
    """A simple service for reading a stream of IntDataArrays.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WriteIntDataArray': grpc.unary_unary_rpc_method_handler(
          servicer.WriteIntDataArray,
          request_deserializer=data_dot_data__pb2.IntDataArray.FromString,
          response_serializer=data_dot_data__pb2.ServerSendResponse.SerializeToString,
      ),
      'GetIntDataArrays': grpc.unary_stream_rpc_method_handler(
          servicer.GetIntDataArrays,
          request_deserializer=data_dot_data__pb2.GetIntDataArrayStreamRequest.FromString,
          response_serializer=data_dot_data__pb2.IntDataArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dataArray.DataServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class DataClientStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.WriteIntDataArray = channel.unary_unary(
        '/dataArray.DataClient/WriteIntDataArray',
        request_serializer=data_dot_data__pb2.IntDataArray.SerializeToString,
        response_deserializer=data_dot_data__pb2.IntDataArray.FromString,
        )


class DataClientServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def WriteIntDataArray(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DataClientServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'WriteIntDataArray': grpc.unary_unary_rpc_method_handler(
          servicer.WriteIntDataArray,
          request_deserializer=data_dot_data__pb2.IntDataArray.FromString,
          response_serializer=data_dot_data__pb2.IntDataArray.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dataArray.DataClient', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
